steps:
  - task: PythonScript@0
    displayName: Download script to download the toolset
    inputs:
      scriptSource: 'inline'
      script: |
        import requests
        request = requests.get("https://raw.githubusercontent.com/aheadlabs/devops-toolset/feature/pythonization/toolset/download_devops-toolset.py")
        with open("$(System.DefaultWorkingDirectory)/.devops/download_devops_toolset.py", "w") as script:
          script.write(request.content.decode("utf-8"))
      failOnStderr: true
  - task: PythonScript@0
    displayName: Download the toolset
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(System.DefaultWorkingDirectory)/.devops/download_devops_toolset.py'
      arguments: '$(System.DefaultWorkingDirectory)/.devops/ --branch=feature/pythonization'
