steps:
  - task: PythonScript@0
    displayName: Download devops-toolset
    inputs:
      scriptSource: 'inline'
      script: |
        import requests
        request = requests.get("https://github.com/aheadlabs/devops-toolset/archive/feature/pythonization.zip")
        with open("$(System.DefaultWorkingDirectory)/.devops/devops-toolset.zip", "wb") as zip_file:
          zip_file.write(request.content)
      failOnStderr: true
  - task: ExtractFiles@1
    displayName: Decompress devops-toolset
    inputs:
      archiveFilePatterns: '$(System.DefaultWorkingDirectory)/.devops/devops-toolset.zip'
      destinationFolder: '$(System.DefaultWorkingDirectory)/.devops'
      cleanDestinationFolder: false
