steps:
  - task: PythonScript@0
    displayName: Get current branch
    inputs:
      scriptSource: 'inline'
      script: |
        import tools.git
        tools.git.set_current_branch_simplified("$(Build.SourceBranch)", "CURRENT_BRANCH")
      failOnStderr: true
  - task: PythonScript@0
    displayName: Parse composer.json
    inputs:
      scriptSource: 'inline'
      script: |
        import project_types.php.parsers as parsers
        parsers.parse_composer_json_data(composer_json_path="$(System.DefaultWorkingDirectory)/composer.json")
      failOnStderr: true
