# Pipeline /.devops/pipeline-build-wpclibackup-ci.yml

trigger:
  batch: true
  branches:
    include:
      - master
      - dev
      - feature/*
      - hotfix/*
      - release/*
pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

name: CI-$(date:yyyyMMdd)$(rev:.r)
jobs:
  - job: Main
    displayName: Main job
    steps:
    - task: CmdLine@2
      displayName: Install tree
      inputs:
        script: sudo apt-get install tree
    - template: pipeline-template-php-setup.yml
    - template: pipeline-template-python-setup.yml
    - template: pipeline-template-devops-toolset.yml
    - task: CmdLine@2
      displayName: Tree files
      inputs:
        script: tree /home/vsts/work/1/s/.devops/devops-toolset/
    - template: pipeline-template-i18n.yml
    - template: pipeline-template-project-info.yml
    #- template: pipeline-template-sonarcloud.yml
